### ISSUE TITLE
3wm support question

### ISSUE THREAD

**Issue by Lennart-Quantware** [kpobrien/JosephsonCircuits.jl#5]
Thanks for the nice package!
`Please note that three wave mixing (3WM) and flux-biasing are relatively untested, so you may encounter bugs. Please file issues or PRs.`
So I tried simulating a 3wm twpa anyway, without much success so far unfortunately.

The first issue I encountered is that it is not possible to enable a DC bias current (`dc=true`) in a circuit which does not have an inductance to ground. (Minimal example of this would be a lowpass filter consisting of a single inductance between 2 ports and capacitance to ground, which produces SingularValue exception)
This can be circumvented by adding a large inductance to ground (~1H), which at least lets me enable the dc option and add a dc bias pump. 

The problem is that I don't know if this actually fixes the problem or just pushes it down the line, since a 3wm twpa with rf-squids does not seem to converge for me. Although the band gap is visible in the resulting S21.

So my question is this: you think it is already possible to simulate a 3wm twpa?

Thanks,
Lennart

**Comment by kpobrien** [comment]
Thanks for filing an issue! Yes, the current requirement for all nodes to be inductively coupled (via an inductor or JJ) and for that inductive network to be connected to ground is a pain. I suspect the way to fix that would be to change the internals from nodal analysis in the node flux basis to modified nodal analysis using node flux and node voltage. I don't have time at the moment to dig into this, but investigations or PRs from others such as yourself would be very welcome. 

>The problem is that I don't know if this actually fixes the problem or just pushes it down the line

In my experience simulating flux pumped JPAs such as the example in the README, the excellent agreement with WRspice suggests it fixes the problem, at least for circuits whose behavior is not significantly changed by this large inductance.

>So my question is this: you think it is already possible to simulate a 3wm twpa?

I think so! If you share a 3WM TWPA with rf-SQUID simulation (ideally based on a published experimental work) in this issue I can take a look. It would be nice to have a 3WM TWPA example.

**Comment by Lennart-Quantware** [comment]
In the attached files my attempt at reproducing 3wm TWPA with a bias current instead of magnetic field.
There is probably something I'm missing, since the resulting S21 is rather similar.
If you could check if the approach makes sense for 3wm twpa that would be great!
(Had to attach them as txt files, since github doesn't let me upload .jl files...)
[test_3wm_twpa_dc_squids.txt](https://github.com/user-attachments/files/15884206/test_3wm_twpa_dc_squids.txt)
[test_3wm_twpa_rf_squids.txt](https://github.com/user-attachments/files/15884207/test_3wm_twpa_rf_squids.txt)

**Comment by kpobrien** [comment]
Thanks! Taking a look at the file implementing "Flux-Driven Josephson Traveling-Wave Parametric Amplifier, A.B. Zorin" overall the structure looks good, but one issue is that mutual inductance needs to couple linear/geometric inductors not JJs. For example, right now Lj_a1_3 and Lj_b1_3 are both between node 1 and node 3. You'll need to modify this so that, for example, the first JJ is from node 1 to node 3, the second is from node 3 to node 4. Then add a linear inductor from node 1 to node 3, then couple that inductor to the pump line via a mutual inductance to provide the flux bias. The flux pumped JPA example follows this structure.
![image](https://github.com/kpobrien/JosephsonCircuits.jl/assets/5942894/ea7a7bc9-684e-4b96-b0ff-afd94e80c527)
I'll try to add a check to error if a user tries to couple a JJ with a mutual inductance to catch this in the future. Happy to take a look at the revised version.

**Comment by Lennart-Quantware** [comment]
Thanks for the fast responses! Indeed directly coupling to a junction doesn't make much sense.
I adjusted the circuit by adding a small linear inductance in the dc-squid loop.
Equation 8 in the paper together with a kappa value mentioned later means I can calculate the mutual inductance necessary.
I then pick the value of the linear squid inductance based on the desired mutual inductance.
The desired dc flux should be a third of the magnetic flux quantum, and I think the way to achieve that would be to drive a bias current Idc = dc_flux / M.
However, this does not converge for me. The only thing that does converge is simulating the circuit with Idc and Ip = 0.
Simulating without pump current takes ~30 seconds for 100 squids, which seems to be unusually slow compared to a 4wm twpa.
This usually means I've made a mistake somewhere with the parameters, but since 3wm is untested I can't really tell.
[test_3wm_twpa_dc_squids_v2.txt](https://github.com/user-attachments/files/15901291/test_3wm_twpa_dc_squids_v2.txt)

Any help is appreciated!

**Comment by kpobrien** [comment]
I think the issues with the v2 netlist are largely device physics. I made a few changes to the netlist and solver parameters and see 3WM gain:
1. Impedance matched the pump transmission line by setting Rdc to 50 Ohms and adding that to both sides. It was terminated with a 1000 Ohm resistor on one side and inductor on the other side.
2. The harmonic balance method may fail to converge either because we haven't picked a good basis (eg. the solution would contain harmonics outside of the chosen set of modes) or because the nonlinear solver doesn't find the solution. We use the Newton-Raphson method with linesearch, which is a fairly basic optimization method. Adding more advanced techniques like homotopy continuation would be valuable, but for now, to improve stability, I dropped the cutoff frequency parameter to 50 GHz and the junction capacitance to the junctions.
3. Tuned the pump inductance to improve phase matching for 3WM.
4. Reduced the number of modes to improve solution speed. I don't see a visual difference but I suggest checking this carefully yourself as well as validating against WRspice or another solver.
```julia
# Paper:
# Flux-Driven Josephson Traveling-Wave Parametric Amplifier, A.B. Zorin

using JosephsonCircuits
using Plots

const magnetic_flux_quantum = 2.0678338484619295e-15
const reduced_magnetic_flux_quantum = magnetic_flux_quantum / (2*pi)

@variables Rport Rdc C Cj L Lpump kappa Lg Lsmall


# From Section V. POSSIBLE CIRCUIT DESIGN
cutoff_frequency = 50e9 # [Hz]

transmission_line_impedance = 50.0

capacitance = 1 / (2 * pi * cutoff_frequency * transmission_line_impedance) # equation (51) [H]
inductance = transmission_line_impedance / (2 * pi * cutoff_frequency) # L = L', equation (52) [F]
critical_current = reduced_magnetic_flux_quantum / inductance

critical_current_density = 3e6 # Typical value mentioned in paper [A/m^2]
jj_area = critical_current / critical_current_density # [m^2]
jj_cap_density = 50 * 1e-15 / (1e-6)^2 # Typical [F/m^2]
jj_capacitance = jj_cap_density * jj_area


nr_cells = 600
modulation_parameter = 0.06

coupling = 0.02 # = M / L', equation (8)
desired_mutual_inductance = coupling * inductance
# Add small linear inductance in dc-SQUID loop to couple pump line inductance with
linear_squid_inductance = desired_mutual_inductance^2 / inductance

optimal_dc_flux = magnetic_flux_quantum / 3 # in order to reduce critical current of dc squid to critical current of junction
Idc = optimal_dc_flux / desired_mutual_inductance

pump_power_watt = 2 * modulation_parameter^2 * reduced_magnetic_flux_quantum^2 * cutoff_frequency^2 / (coupling^2 * transmission_line_impedance * tan(optimal_dc_flux / 2 / reduced_magnetic_flux_quantum)^2) # equation (14)
Ip = sqrt(2 * pump_power_watt / transmission_line_impedance) # [A]

pump_frequency = 20e9 # [Hz]
frequency_detuning = range(-0.5, 1.5, 500)
signal_frequency = pump_frequency / 2 .* (frequency_detuning .+ 1)

circuit = Tuple{String,String,String,Num}[]
entry = (elem, n1, n2, value) -> push!(circuit, ("$(elem)$(n1)_$(n2)", "$n1", "$n2", value))

function build_circuit()
    node = 1

    node_p1 = node # P1: Start of transmission line
    entry("P", node_p1, 0, 1)
    entry("R", node_p1, 0, Rport)
    entry("L", node_p1, 0, Lg)

    node_p3 = node+1 # P3: Start of pump line
    entry("P", node_p3, 0, 3)
    entry("R", node_p3, 0, Rdc)

    for cell_index in 1:nr_cells
        entry("C", node, 0, C)
        entry("Lj_a", node, node+3, L)
        entry("Cj_a", node, node+3, Cj)
        entry("L", node, node+2, Lsmall)
        entry("Lj_b", node+2, node+3, L)
        entry("Cj_b", node+2, node+3, Cj)

        pump_line_inductor_end_node = node+4
        # ground end of pump line
        if cell_index == nr_cells
            pump_line_inductor_end_node = 0
            entry("P", node+1, 0, 4)
            entry("R", node+1, 0, Rdc)
            entry("L", node+1, 0, Lg)
        else
            entry("L", node+1, pump_line_inductor_end_node, Lpump)
            entry("C", node+1, 0, C)
            push!(circuit, ("K$(node)", "L$(node)_$(node+2)", "L$(node+1)_$(pump_line_inductor_end_node)", kappa))
    end

        node += 3
    end

    entry("P", node, 0, 2) # P2: End of transmission line
    entry("R", node, 0, Rport)
end

build_circuit()

circuitdefs = Dict(
    kappa => 0.999, # M = kappa * sqrt(linear_squid_inductance * L') = coupling * L', kappa needs to be < 1
    Lg => 10.0e-9, # inductance to ground, required for solver
    Rport => 50.0,
    Rdc => 50.0,
    C => capacitance,
    L => inductance,
    Lpump => 1.25*inductance,
    Lsmall => linear_squid_inductance,
    Cj => jj_capacitance,
)

ws = 2*pi*signal_frequency
wp = (2*pi*pump_frequency,)

# add the DC bias and pump to port 3
sourcespumpon = [(mode=(0,),port=3,current=Idc),(mode=(1,),port=3,current=18*Ip)]
Npumpharmonics = (8,)
Nmodulationharmonics = (4,)
@time sol = hbsolve(ws, wp, sourcespumpon, Nmodulationharmonics,
    Npumpharmonics, circuit, circuitdefs;
    dc = true, threewavemixing=true,fourwavemixing=true,
    switchofflinesearchtol=0.0,alphamin=1e-7,iterations=200) # enable dc and three wave mixing

p1=plot(sol.linearized.w/(2*pi*1e9),
    10*log10.(abs2.(sol.linearized.S(
            outputmode=(0,),
            outputport=2,
            inputmode=(0,),
            inputport=1,
            freqindex=:),
    )),
    ylim=(-40,30),label="S21",
    xlabel="Signal Frequency (GHz)",
    legend=:bottomright,
    title="Scattering Parameters",
    ylabel="dB")

plot!(sol.linearized.w/(2*pi*1e9),
    10*log10.(abs2.(sol.linearized.S((0,),1,(0,),2,:))),
    label="S12",
    )

plot!(sol.linearized.w/(2*pi*1e9),
    10*log10.(abs2.(sol.linearized.S((0,),1,(0,),1,:))),
    label="S11",
    )

plot!(sol.linearized.w/(2*pi*1e9),
    10*log10.(abs2.(sol.linearized.S((0,),2,(0,),2,:))),
    label="S22",
    )

p2=plot(sol.linearized.w/(2*pi*1e9),
    sol.linearized.QE((0,),2,(0,),1,:)./sol.linearized.QEideal((0,),2,(0,),1,:),    
    ylim=(0,1.05),
    title="Quantum efficiency",legend=false,
    ylabel="QE/QE_ideal",xlabel="Signal Frequency (GHz)");

p3=plot(sol.linearized.w/(2*pi*1e9),
    10*log10.(abs2.(sol.linearized.S(:,2,(0,),1,:)')),
    ylim=(-40,30),
    xlabel="Signal Frequency (GHz)",
    legend=false,
    title="All idlers",
    ylabel="dB")

p4=plot(sol.linearized.w/(2*pi*1e9),
    1 .- sol.linearized.CM((0,),2,:),    
    legend=false,title="Commutation \n relation error",
    ylabel="Commutation \n relation error",xlabel="Signal Frequency (GHz)");

plot(p1, p2, p3, p4, layout = (2, 2))
```
```
 13.713995 seconds (2.26 M allocations: 2.349 GiB, 0.32% gc time)
```
![image](https://github.com/kpobrien/JosephsonCircuits.jl/assets/5942894/39295f1d-8221-4926-80fd-4460b311df1b)

I noticed a few unexpected things from the simulation results:
1. The required pump current is much larger than your prediction, 18x in the simulation above. The DC current seems spot on for minimizing 4WM processes.
2. Depending on the phase matching and pump current, there are spikes of forward and reverse gain. You can look at the other modes to determine the origin. 
3. It's not clear to me whether the above operating point could actually be reached in an experiment because for lower pump currents  (eg. this is for 15x)  I see large values of gain near the pump frequency which would probably trigger parametric oscillation (although lossy capacitors will help stability in an exp.):
![image](https://github.com/kpobrien/JosephsonCircuits.jl/assets/5942894/acbebc4f-ebbd-4f86-a4a3-d8713f8dcf21)

As next steps, I suggest further reducing the cutoff frequency to try to reduce some of these spurious processes, then simulate the same system in WRspice or another solver to validate. I would also double check the pump current prediction formula. In a sense, this already makes a great example since it shows the impact of processes other than the one you want, but for new users it's probably best to find parameters that give a more stable operating point.

**Comment by Lennart-Quantware** [comment]
Amazing!

1. The pump line was copied from the JPA example, makes sense that this is not impedance matched.
2. I'm very interested in knowing more about why the HB method does not converge: it would be greatly insightful if I can somehow figure out why it is not converging, but for now I can indeed try to reduce the cutoff frequency to prevent higher harmonics from spawning.
3. Adjusting the pump impedance also changes the flux going through the squid, since the Idc is targeted for the preadjusted pump impedance. I can't quickly find an optimal pump impedance that works for arbitrary critical current and pump current. My guess would be that the interaction between the squid line and the pump line influences the SQUID inductance and hence also the bias needed to suppress 4WM.


After the fixes you made, I tried to follow your suggestion and made the following improvements:
1. The required pump being larger than the prediction is because the prediction does not account for the weak coupling (Idc was correctly adjusted). If you take into account the weak coupling, it is equivalent to simply define `Ip = modulation_parameter * Idc`.

2. Since the pump line inductance was adjusted after the other circuit parameters have been calculated, the pump line was no longer impedance matched. So I changed the pump line capacitance to target 50.0 Ohms using the updated pump line inductance, which got rid of a lot of peaks and ripple.

3. In order to reduce reflections, I updated the twpa circuit to start and end with `C/2`.

4. I believe the necessary Lg can have a significant impact on the performance: given a junction capacitance of 32 fF, together with the inductance to ground of ~ 10 nH can form a simple high pass filter of ~ 6 GHz. This might cause reflections and thus peaks. I found that 
the inductance has minimal impact when placed at the end of the pump line. (it is not necessary to place one in the squid line)

For now I think this is already a nice example to add to the repository, let me know if you want me to make a PR!

Thanks for all the help,
![test_3wm_twpa_dc_squids_v4.txt](https://github.com/user-attachments/files/15955894/test_3wm_twpa_dc_squids_v4.txt)
![3wm_dc_squid_example](https://github.com/kpobrien/JosephsonCircuits.jl/assets/141329563/0de52530-dd2e-4ee0-b390-4166d2bd579b)

Lennart

**Comment by kpobrien** [comment]
Good! Yes, please do make a PR to add this example. I think it's best to add it at the end since it's the most complex of the examples. The only remaining thing is to simulate this system in WRspice to validate the HB simulations. 

Regarding convergence, I'm also interested in improving that. I'd start with an easier case like a single or double pumped TWPA. I suspect either (1) there is an error in the function or Jacobian calculation that only becomes significant in these cases or (2) we need a better nonlinear solver method than Newton with linesearch. Careful validation of the output relative to another solver in the poorly converging regions and analysis of the convergence / trying out other solvers are my suggested paths forward. If you or others are interested in digging into this, please open another issue. Thanks!
